### ISSUE TITLE
Include license file in pypi package

### ISSUE THREAD

**Issue by djmattyg007** [paulgb/simplediff#28]
The license text should always accompany every copy of the code.

**Comment by paulgb** [comment]
It’s been a while since I’ve touched python packaging so I’m not sure how to add non-python files to the package, but I’d accept a PR for this.

**Comment by djmattyg007** [comment]
I created #29 to resolve this :+1:

**Comment by djmattyg007** [comment]
Solved! Thank you for acting on this so quickly!
